export {default as Statistics1} from './Statistics1/Statistics1'
export {default as Statistics2} from './Statistics2/Statistics2'
export {default as Statistics3} from './Statistics3/Statistics3'
export {default as Statistics4} from './Statistics4/Statistics4'
export{default as Portfolio} from './portfolio/Portfolio'